version: '2'

# prerequisites
# -

# example usage: docker-compose -f compose-mysql-mongodb.yml up

services:
  crud-and-search-app:
    build: crud-and-search-app
    container_name: crud-and-search-app
    networks:
      localbridge:
        aliases:
          - crud-and-search

  crud-and-search-mysql:
    image: mysql
    container_name: crud-and-search-mysql
    ports:
      - '3306:3306'
    networks:
      localbridge:
        aliases:
          - crud-and-search
    environment:
      MYSQL_ROOT_PASSWORD: agillaire

  crud-and-search-elasticsearch:
      image: elasticsearch
      container_name: crud-and-search-elasticsearch
      ports:
        - '9200:9200'
        - '9300:9300'
      networks:
        localbridge:
          aliases:
            - crud-and-search

networks:
  localbridge:
    driver: bridge
