version: '2'

# prerequisites
# - ./data/mysql/db initialized by running compose-mysql.yml and then ./data/mysql/ddl/sample-ddl.sql into it
# - ./data/mongo/db initialized by running compose-mongo.yml and then ./data/mongo/ddl/sample-ddl.sql into it

# example usage: docker-compose -f compose-es-mysql-mongo.yml up

services:

  crud-and-search-mysql:
    image: mysql
    container_name: crud-and-search-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      localbridge:
        aliases:
          - crud-and-search
    environment:
      MYSQL_DATABASE: agillaire

  crud-and-search-mongodb:
    image: mongo
    container_name: crud-and-search-mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo/db:/data/db/
    networks:
      localbridge:
        aliases:
          - crud-and-search

  crud-and-search-elasticsearch:
      image: elasticsearch
      container_name: crud-and-search-elasticsearch
      ports:
        - '9200:9200'
        - '9300:9300'
      networks:
        localbridge:
          aliases:
            - crud-and-search

networks:
  localbridge:
    driver: bridge
