version: '2'

# prerequisites
# -

# example usage: docker-compose -f compose-mongodb.yml up

services:
  crud-and-search-mongodb:
      image: mongo
      container_name: crud-and-search-mongodb
      ports:
        - '27017:27017'
      volumes:
        - ./data/mongodb/db:/data/db/
      networks:
        localbridge:
          aliases:
            - crud-and-search

networks:
  localbridge:
    driver: bridge
