version: '2'

# prerequisites
# -

# example usage: docker-compose -f compose-mysql.yml up

services:
  persist-and-search-mysql:
    image: mysql
    container_name: persist-and-search-mysql
    ports:
      - '3306:3306'
    networks:
      localbridge:
        aliases:
          - persist-and-search
    environment:
      MYSQL_ROOT_PASSWORD: agillaire

networks:
  localbridge:
    driver: bridge
