version: '2'

# prerequisites
# -

# example usage: docker-compose -f compose-es-mysql-mongo.yml up

services:

  crud-and-search-mysql:
    build:
      context: .
      dockerfile: dockerfile-mysql
    container_name: crud-and-search-mysql
    ports:
      - '3306:3306'
    networks:
      localbridge:
        aliases:
          - crud-and-search

  crud-and-search-mongodb:
    image: mongo
    container_name: crud-and-search-mongodb
    ports:
      - '27017:27017'
    networks:
      localbridge:
        aliases:
          - crud-and-search

  crud-and-search-elasticsearch:
      image: elasticsearch
      container_name: crud-and-search-elasticsearch
      ports:
        - '9200:9200'
        - '9300:9300'
      networks:
        localbridge:
          aliases:
            - crud-and-search

networks:
  localbridge:
    driver: bridge
